# Generated by Django 4.2 on 2024-10-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A2ZzPP', '0004_remove_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='A2ZzPP.product'),
        ),
    ]
